const PAGE_NUMBER_DEFAULT = 1;
const PAGE_SIZE_DEFAULT = 10;

const ROLE = {
  ADMIN: 'ADMIN',
  OWNER: 'OWNER',
};

const VIDEO_STATUS = {
  PROCESSING: 'PROCESSING',
  ERROR: 'ERROR',
  DONE: 'DONE'
}

module.exports = {
  PAGE_NUMBER_DEFAULT,
  PAGE_SIZE_DEFAULT,
  ROLE,
  VIDEO_STATUS,
};
